# baseURL = "http://acnil.es/"
baseURL = "/"
languageCode = 'en-us'
title = 'Asociacion Cultural ACNIL'

theme = "paper"

[params]
  # header social icons
  twitter = 'acnilburgos'               # twitter.com/YOUR_TWITTER_ID
  instagram = 'acnilburgos'           # instagram.com/YOUR_INSTAGRAM_ID

  # home page profile
  # avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  # name = 'YOUR_NAME'
  # bio = 'YOUR_BIO'


  # misc
  comments = false   
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  # gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  # math = true                               # enable KaTex math typesetting globally

[markup.goldmark.renderer]
unsafe= true