baseURL = "http://localhost:1313/acnil/"
# baseURL = "/"
languageCode = 'en-us'
title = 'ACNIL'
mainSections = "blog"

RelativeURLs=true
CanonifyURLs=true

# I based the website on this, but I removed all unnecessary code to make it easier to understand
# https://github.com/nanxiaobei/hugo-paper
# theme = "paper"

refLinksErrorLevel="WARNING"

[params]
  # header social icons
  twitter = 'acnilburgos'               
  instagram = 'acnilburgos'           
  github = 'acnil'

  # home page profile
  # avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  # name = 'YOUR_NAME'
  # bio = 'YOUR_BIO'


  # misc
  comments = false   
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                     # show monochrome dark mode icon
  # math = true                               # enable KaTex math typesetting globally

[markup.goldmark.renderer]
unsafe= true
